

class StaticVariables():
    MAIN_PAGE_STRING = 'MainPage'
    RESULT_LIST_STRING = 'ResultListPage'
    ON_STRING = 'ON'
    OFF_STRING = 'OFF'
    ERROR_STRING = 'ERROR'
    LOG_EXTENTION = '.log'
    LOG_FINDER = 'Log Finder'
    HELP_STRING = 'Help'
    OPEN_FOLDER_PATH = './static/png/open_folder.png'
    SEARCH_LOGO_PATH = './static/png/search_logo.png'
    ON_DEBUG_PATH = 'static/png/debug/ON.png'
    OFF_DEBUG_PATH = 'static/png/debug/OFF.png'
    MAIN_PAGE_LOGO = 'static/png/main_page_logo.png'
    HELP_LOGO = 'static/png/help_icon.png'
    BACK_LOGO = 'static/png/back_logo.png'
    APP_ICON = 'static/ico/app_icon.ico'
    HELP_PHOTOS_PATH = 'static/png/help'
    SMALL_BACK_BUTTON = 'static/png/small_back_logo.png'
    SMALL_NEXT_BUTTON = 'static/png/small_next_logo.png'
    NO_RESULT_STRING = 'No Results'
    NO_RESULTS_RETURNED = 'No Results Returned'
    PATH_ERROR_STRING = 'Path Error'
    NO_PATH_SELECTED_STRING = 'No Path Selected Or Wrong Path'
    SEARCH_ERROR_STRING = 'Search Error'
    NO_KEYWORD_WRITEN_STRING = 'No Keyword Writen'
